### ISSUE TITLE
请问下架构图,训练结果图是如何生成的

### ISSUE THREAD

**Issue by xxmyjk** [JasonLiTW/simple-railway-captcha-solver#1]
我是一个前端...目前在做可视化方面的工作, 麻烦问下你的架构图 (11.png)和训练结果图(12.png)是如何生成的?

谢谢~~

**Comment by JasonLiTW** [comment]
在[Callback](https://github.com/JasonLiTW/simple-railway-captcha-solver#callback)的地方有用到[TensorBoard](https://github.com/JasonLiTW/simple-railway-captcha-solver#3tensorboard)，透過它就可以用圖形化介面檢視輸出的結果了，架構圖的部分裡面也會有的(在GRAPHS中)。

```python
tensorBoard = TensorBoard(log_dir = "./logs", histogram_freq = 1)
```
這邊會把每個epoch的log存到./logs中，接著你只需要到根目錄下這行指令：
```
tensorboard --logdir=logs
```
就可以啟動tensorboard了，他會告訴你在執行在電腦上的哪個port，通常是6006(也就是去瀏覽器輸入localhost:6006，就會有一切你需要的資料了~)

更詳細的設定可以參考Keras的官方文件：https://keras.io/callbacks/#tensorboard
