### ISSUE TITLE
您好，有Capsule Network識別驗證碼的demo？

### ISSUE THREAD

**Issue by etimes2008** [JasonLiTW/simple-railway-captcha-solver#3]
您好，有Capsule Network識別驗證碼的demo？能不能提供參考呢

**Comment by JasonLiTW** [comment]
Capsule network的部分，我是參考[這個repo](https://github.com/XifengGuo/CapsNet-Keras)修改的，但不知為何實際使用效果比CNN差，所以就不貼上來了，您可以到該repo參考一下～
