### ISSUE TITLE
train_cnn_real_4.py 错误

### ISSUE THREAD

**Issue by nu1ee** [JasonLiTW/simple-railway-captcha-solver#4]
因为我的验证码是4位自行修改了下：
 这个怎么解决？

`  File "train_cnn_real_4.py", line 24
    in = Input((60, 200, 3))
     ^
SyntaxError: invalid syntax `

将：`in = Input((60, 200, 3))`改为`ina = Input((60, 200, 3))` 
`D:\NUTCPserver\att\simple-railway-captcha-solver>py -3 train_cnn_real_4.py
  File "train_cnn_real_4.py", line 50
    model = Model(inputs=in, outputs=out)
        ^
SyntaxError: invalid syntax`
这里改变量也无效
```
D:\NUTCPserver\att\simple-railway-captcha-solver>py -3 train_cnn_real_4.py
  File "train_cnn_real_4.py", line 50
    model = Model(inputs=ina, outputs=out)
        ^
SyntaxError: invalid syntax

D:\NUTCPserver\att\simple-railway-captcha-solver>py -3 train_cnn_real_4.py
  File "train_cnn_real_4.py", line 50
    modela = Model(inputs=ina, outputs=out)
         ^
SyntaxError: invalid syntax

D:\NUTCPserver\att\simple-railway-captcha-solver>py -3 train_cnn_real_4.py
  File "train_cnn_real_4.py", line 50
    model = Model(inputs=ina, outputs=out)
        ^
SyntaxError: invalid syntax
```

train_cnn_real_5.py运行也是一样

```
D:\NUTCPserver\att\simple-railway-captcha-solver>py -3 train_cnn_real_5.py
  File "train_cnn_real_5.py", line 24
    in = Input((60, 200, 3))
     ^
SyntaxError: invalid syntax
```

**Comment by JasonLiTW** [comment]
不好意思有點晚回覆，
要將輸出改變數目，應該要試著改模型最上方的Dense Layer的數量才對，
至於其他錯誤，可能要請你把完整的code貼上來，這邊還看不出來是哪邊出了問題
