### ISSUE TITLE
Training_label 格式問題

### ISSUE THREAD

**Issue by wilile26811249** [JasonLiTW/simple-railway-captcha-solver#5]
如果照README.md裡面寫的-> 將6個array放到一個list
這樣在train的時候, trainLabel會遇到這個問題:
        Expected to see 4 array(s), but instead got the following list of 1 arrays

**Comment by JasonLiTW** [comment]
這個應該是keras新版要求y也必須要是numpy array的關係，改成將那6個放進1個numpy array就行了:)
